CREATE DATABASE rkis;

\connect rkis

CREATE TABLE IF NOT EXISTS Dishes (
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name     VARCHAR,
    color    VARCHAR,
    material VARCHAR,
    width   NUMERIC,
    depth    NUMERIC,
    price    NUMERIC,
    quantity INTEGER
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR,
    password VARCHAR,
    role VARCHAR
);